main/urls.py
from django.urls import path


from . import views


# ルーティング情報を列挙する
urlpatterns = [
    path('', views.index, name='index'),
    path('temp', views.temp, name='temp'),
    path('list', views.list, name='list'),
    path('iftag', views.iftag, name='iftag'),
    path('yesno', views.yesno, name='yesno'),
    path('firstof', views.firstof, name='firstof'),
    path('forloop', views.forloop, name='forloop'),
    path('forempty', views.forempty, name='forempty'),
    path('fortag', views.fortag, name='fortag'),
    path('ifchanged', views.ifchanged, name='ifchanged'),
    path('regroup', views.regroup, name='regroup'),
    path('cycle', views.cycle, name='cycle'),
    path('escape', views.escape, name='escape'),
    path('temptag', views.temptag, name='temptag'),
    path('verbatim', views.verbatim, name='verbatim'),
    path('master', views.master, name='master'),
    path('include', views.include, name='include'),
    path('static', views.static, name='static'),
    path('slice', views.slice, name='slice'),
    path('date_time', views.date_time, name='date_time'),
    path('filter', views.filter, name='filter'),
    path('exclude', views.exclude, name='exclude'),
    path('get', views.get, name='get'),
    path('filter_or', views.filter_or, name='filter_or'),
    path('filter_other', views.filter_other, name='filter_other'),
    path('groupby', views.groupby, name='groupby'),
    path('union', views.union, name='union'),
    path('rel', views.rel, name='rel'),
    path('rel2', views.rel2, name='rel2'),
    path('route_param/<int:id>', views.route_param, name='route_param'),
    path('search/<path:keywd>', views.search, name='search'),
    path('req_query', views.req_query, name='req_query'),
    path('req_header', views.req_header, name='req_header'),
    path('req_redirect', views.req_redirect, name='req_redirect'),
    path('details/<int:id>', views.details, name='details'),
    path('res_notfound', views.res_notfound, name='res_notfound'),
    path('setcookie', views.setcookie, name='setcookie'),
    path('getcookie', views.getcookie, name='getcookie'),
    path('setsession', views.setsession, name='setsession'),
    path('getsession', views.getsession, name='getsession'),
    path('form_input', views.form_input, name='form_input'),
    path('form_process', views.form_process, name='form_process'),
    path('crud_new', views.crud_new, name='crud_new'),
    path('crud_create', views.crud_create, name='crud_create'),
    path('crud_edit/<int:id>', views.crud_edit, name='crud_edit'),
    path('crud_update/<int:id>', views.crud_update, name='crud_update'),
    path('crud_show/<int:id>', views.crud_show, name='crud_show'),
    path('crud_delete/<int:id>', views.crud_delete, name='crud_delete'),

]

quick_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # main/urls.pyをインポート
    path('main/',include('main.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import RegexValidator, MinValueValidator

class Book(models.Model):
  isbn = models.CharField(
    verbose_name='ISBNコード',
    max_length=20,
    validators=[
      RegexValidator(
        r'^978-4-[0-9]{4}-[0-9]{4}-[0-9X]{1}$',
        message='ISBNコードは正しい形式で指定してください。')
    ]
  )
  title = models.CharField(
    verbose_name='書名',
    max_length=100
  )
  price = models.IntegerField(
    verbose_name='価格',
    default = 0,
    validators=[
      MinValueValidator(
        17,
        message='価格は正の整数で指定してください。'
      )
    ]
  )
  publisher = models.CharField(
    verbose_name='出版社',
    max_length=50,
    choices = [
      ('翔泳社', '翔泳社'),
      ('技術評論社', '技術評論社'),
      ('秀和システム', '秀和システム'),
      ('SBクリエイティブ', 'SBクリエイティブ'),
      ('日経BP', '日経BP'),
    ],
  )
  published = models.DateField(
      verbose_name='刊行日'
  )
  def __str__(self):
    return f'{self.title}({self.publisher}/{self.price}円)'

  # class Meta:
  #     ordering = ('published',)

  def get_absolute_url(self):
    return f'details/{self.id}'

class Review(models.Model):
  book = models.ForeignKey(Book, on_delete=models.CASCADE)
  name = models.CharField(
    verbose_name='名前',
    max_length=20
  )
  body = models.TextField(
    verbose_name='本文',
    max_length=255
  )
  def __str__(self):
    return f'{self.name}: {self.body[:10]}'

class Author(models.Model):
  books = models.ManyToManyField(Book)
  name = models.CharField(
    verbose_name='名前',
    max_length=20
  )
  address = models.CharField(
    verbose_name='住所',
    max_length=100
  )
  def __str__(self):
    return self.name

class User(models.Model):
  author = models.OneToOneField(Author, on_delete=models.CASCADE)    
  handle = models.CharField(
    verbose_name='ユーザー名',
    max_length=20
  )
  email = models.CharField(
    verbose_name='メールアドレス',
    max_length=100
  )
  def __str__(self):
    return self.handle

main/forms.py
from django import forms
from datetime import date
from .validates import compare_today
from .models import Book


class BookModelForm(forms.ModelForm):
  class Meta:
    model = Book
    fields = ('isbn', 'title', 'price', 'publisher', 'published')
    
# a.フォームを定義
class BookForm(forms.Form):
  isbn = forms.CharField(label='ISBNコード',
    required=True, max_length=20,
    error_messages={
      'required': 'ISBNコードは必須です。',
      'max_length': 'ISBNコードは20文字以内で入力してください。'
    })
  title = forms.CharField(label='書名',
    required=True, max_length=100,
    error_messages={
      'required': '書名は必須です。',
      'max_length': '書名は100文字以内で入力してください。'
    })
  price = forms.IntegerField(label='価格',
    required=True, min_value=0,
    error_messages={
      'required': '価格は必須です。',
      'min_value': '価格は正数で入力してください。',
    })
  publisher = forms.ChoiceField(label='出版社',
    # widget=forms.RadioSelect(),

  # publisher = forms.MultipleChoiceField(label='出版社',
  #   widget=forms.SelectMultiple(attrs={ 'size': 5 }),
    choices = [
      ('翔泳社', '翔泳社'),
      ('技術評論社', '技術評論社'),
      ('秀和システム', '秀和システム'),
      ('SBクリエイティブ', 'SBクリエイティブ'),
      ('日経BP', '日経BP'),
    ])
  published = forms.DateField(label='刊行日',
    required=True,
    validators=[compare_today],
    error_messages={
      'required': '刊行日は必須です。',
      'invalid': '刊行日はYYYY-MM-DDの形式で入力してください。'
    })
def clean(self):
    cleaned_data = super().clean()
    isbn = cleaned_data.get('isbn')
    published = cleaned_data.get('published')
    if isbn and published:
      if published.year < 2007:
        if len(isbn) != 13:
          raise forms.ValidationError('ISBNコードは13桁で入力してください。')
      else:
        if len(isbn) != 17:
          raise forms.ValidationError('ISBNコードは17桁で入力してください。')

class UploadForm(forms.Form):
  body = forms.FileField()

main/views.py
import csv
import random
import tempfile
import urllib.parse
from datetime import date
from datetime import datetime

from django.contrib import messages
from django.db.models import Q
from django.db.models import Count
from django.db.models.functions import Substr

from django.http import FileResponse
from django.http import Http404
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.http import require_GET
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from .forms import BookForm
from .forms import  BookModelForm
from .forms import UploadForm
from .models import Book

# a.リクエスト情報を受け取る
def index(request):
    # b.レスポンスを生成する
    return HttpResponse('こんにちは、世界！')

def temp(request):
    # a.ビュー変数を準備
    context = {
        'msg': 'こんにちは、世界！'
    }
    # b.テンプレートを呼び出す
    return render(request, 'main/temp.html', context)

def list(request):
    # すべての書籍情報を取得
    books = Book.objects.all()
    return render(request, 'main/list.html',{
        'books': books
    })

def iftag(request):
  rand = random.randint(0, 100)
  return render(request, 'main/iftag.html', {
    'random': rand
  })
  
def yesno(request):
  return render(request, 'main/yesno.html', {
    'flag': True
  })

def firstof(request):
    return render(request, 'main/firstof.html', {
        # 'a': 'おはようございます！',
        # 'b': 'こんにちは！',
         'c': 'こんばんは！'
    })
    
def forloop(request):
    return render(request, 'main/forloop.html', {
        'weeks': ['月', '火', '水', '木', '金', '土', '日']
    })
    
def forempty(request):
    return render(request, 'main/forempty.html', {
        'members': ['鈴木三郎', '佐藤洋子', '山田次郎']
    })
    
def fortag(request):
    return render(request, 'main/fortag.html')

def ifchanged(request):
    return render(request, 'main/ifchanged.html', {
        'schedule': [
            (10, 'A企画反省会'),
            (10, 'B書籍脱稿'),
            (15, 'WINGS定例会議'),
            (30, 'C企画打ち合わせ'),
        ]
    })
    
def regroup(request):
    # a.メンバー情報を準備
    return render(request, 'main/regroup.html', {
        'members': [
            {'name': '鈴木三郎', 'sex': '男', 'birth': '1980-12-23' },
            {'name': '山田次郎', 'sex': '男', 'birth': '1978-10-13' },
            {'name': '佐藤健司', 'sex': '男', 'birth': '1976-04-06' },
            {'name': '山本花子', 'sex': '女', 'birth': '1981-07-28' },
            {'name': '田中久美', 'sex': '女', 'birth': '1980-09-07' },
        ]
    })

def cycle(request):
    # a.メンバー情報を準備
    return render(request, 'main/cycle.html', {
        'members': [
            {'name': '鈴木三郎', 'sex': '男', 'birth': '1980-12-23' },
            {'name': '山田次郎', 'sex': '男', 'birth': '1978-10-13' },
            {'name': '佐藤健司', 'sex': '男', 'birth': '1976-04-06' },
            {'name': '山本花子', 'sex': '女', 'birth': '1981-07-28' },
            {'name': '田中久美', 'sex': '女', 'birth': '1980-09-07' },
        ]
    })
    
def escape(request):
    return render(request, 'main/escape.html', {
        'msg': '''<img src="https://wings.msn.to/image/wings.jpg" title="ロゴ" />
        <p>WINGSへようこそ</p>'''
    })

def temptag(request):
    return render(request, 'main/temptag.html')

def verbatim(request):
    return render(request, 'main/verbatim.html')

def master(request):
    # a.呼び出すのは子テンプレート
    return render(request, 'main/master.html', {
        'msg': 'こんにちは世界！',
    })
    
def include(request):
    return render(request, 'main/include.html', {
        'name': '鈴木',
        'current': datetime.datetime.now(),
    })
    
def static(request):
    return render(request, 'main/static.html')

def slice(request):
    return render(request, 'main/slice.html', {
        'data': ['い', 'ろ', 'は', 'に', 'ほ', 'へ']
    })
    
def date_time(request):
    return render(request, 'main/date_time.html', {
        'today': datetime.now()
    })

def filter(request):
#   books = Book.objects.filter(publisher='翔泳社')

  # AND条件
#   books = Book.objects.filter(publisher='翔泳社', price=3300)

  # 大小比較
#   books = Book.objects.filter(price__lt = 3000)

  # 部分一致
#   books = Book.objects.filter(title__contains = '独習')

  # 正規表現比較
#   books = Book.objects.filter(title__regex = r'[0-9]+')

  # NULL比較
  # books = Book.objects.filter(title__isnull = True)

  # 範囲比較
  # books = Book.objects.filter(published__range = 
  #   (date(2018, 1, 1), date(2018, 12, 31)))

  # 候補比較
  books = Book.objects.filter(publisher__in = ['翔泳社', '技術評論社', '日経BP'])

  # 日付比較（年／月／日）
  # books = Book.objects.filter(published__year = 2019)
  # books = Book.objects.filter(published__year__lte = 2019)
  # books = Book.objects.filter(published__week_day__range = (2, 6))

  return render(request, 'main/book_list.html', {
    'books': books
  })

def exclude(request):
    # 出版社が翔泳社である書籍情報を除去
    books = Book.objects.exclude(publisher='翔泳社')
    return render(request, 'main/book_list.html', {
        "books": books
    })
    
def get(request):
    # 主キーが1である書籍情報を取得
    book = Book.objects.get(pk=1)
    return render(request, 'main/book_list.html', {
        "book": book
    })
    
def filter_or(request):
    books = Book.objects.filter(
        Q(publisher='翔泳社') | Q(price__gte=2800))
    return render(request, 'main/book_list.html', {
        "books": books
    })
    
def filter_other(request):
    books = Book.objects.order_by('publisher', 'published')
    return render(request, 'main/book_list.html', {
        "books": books
    })
    
def groupby(request):
    return render(request, 'main/groupby.html', {
        'groups': Book.objects.values('publisher')
        .annotate(pub_count=Count('publisher')).order_by('-pub_count')
    })
    
def union(request):
    b1 = Book.objects.filter(publisher = '翔泳社')
    b2 = Book.objects.filter(publisher = '技術評論社')
    return render(request, 'main/list.html', {
        "books": b1.union(b2)
    })
    
def rel(request):
    return render(request, 'main/rel.html', {
        'book': Book.objects.get(pk=1)
    })
    
def rel2(request):
    return render(request, 'main/rel2.html', {
        'books' : Book.objects.all()
    })
    
def search(request, keywd):
  return HttpResponse(f'パラメーター：{keywd}')

def route_param(request, id):
    return HttpResponse(f'id値: {id}')
    
def req_query(request):
  return HttpResponse(f'id値：{request.GET["id"]}')

def req_header(request):
  return HttpResponse(f'Use-Agent： {request.headers["User-Agent"]}')

def req_redirect(request):
  # return redirect('list')
  # return redirect('http://wings.msn.to/', permanent=True)
  # return redirect('route_param', id=10)

  # path = reverse('route_param', kwargs={ 'id': 1 })
  # return HttpResponse(path)
  
  book = Book.objects.get(pk=1)
  return redirect(book)

def details(request, id):
  return HttpResponse(f'id値：{id}')

def res_notfound(request):
    try:
        book = Book.objects.get(pk=108)
    except Book.DoesNotExist:
        raise Http404('指定の書籍情報が存在しません。')
    return render(request, 'main/book_detail.html', {
        'book': book
    })
    
def setcookie(request):
  response = HttpResponse(render(request, 'main/setcookie.html'))
  response.set_cookie('app_title',
    urllib.parse.quote('速習Django'), 60 * 60 * 24 * 30, samesite='Strict')
  return response
#   return redirect('http://wings.msn.to/')

def getcookie(request):
  app_title = urllib.parse.unquote(request.COOKIES['app_title']) \
    if 'app_title' in request.COOKIES else '－'
  return render(request, 'main/getcookie.html', {
    'app_title': app_title
  })
  
def setsession(request):
  request.session['app_title'] = '速習Django'
  return HttpResponse('セッションを保存しました。')

def getsession(request):
  title = request.session['app_title'] \
    if 'app_title' in request.session else '－' 
  return HttpResponse(title)

def form_input(request):
    # a.フォームオブジェクトを生成
    form = BookForm()
    return render(request, 'main/form_input.html', {
        'form': form
    })

@require_POST
def form_process(request):
  form = BookForm(request.POST)
  if form.is_valid():
    return render(request, 'main/form_process.html', {
      'form': form
    })
  else:
    return render(request, 'main/form_input.html', {
      'form': form
    })

def crud_new(request):
  form = BookModelForm()
  return render(request, 'main/crud_new.html', {
    'form': form
  })

@require_POST
def crud_create(request):
  obj = Book()
  form = BookModelForm(request.POST, instance=obj)
  if form.is_valid():
    form.save()
    messages.add_message(request, messages.SUCCESS,
      'データの保存に成功しました。')
    return redirect('crud_new')
  else:
    return render(request, 'main/crud_new.html', {
      'form': form
    })

def crud_edit(request, id):
  obj = Book.objects.get(pk=id)
  form = BookModelForm(instance=obj)
  return render(request, 'main/crud_edit.html', {
    'id': id,
    'form': form
  })

@require_POST
def crud_update(request, id):
  obj = Book.objects.get(pk=id)
  form = BookModelForm(request.POST, instance=obj)
  if form.is_valid():
    form.save()
    messages.set_level(request, messages.WARNING)
    messages.success(request, 'データの更新に成功しました。')
    return redirect(reverse('crud_edit', kwargs={ 'id': id }))
  else:
    return render(request, 'main/crud_edit.html', {
      'id': id,
      'form': form
    })

def crud_show(request, id):
  obj = Book.objects.get(pk=id)
  form = BookModelForm(instance=obj)
  return render(request, 'main/crud_show.html', {
    'id': id,
    'form': form
  })

@require_POST
def crud_delete(request, id):
  obj = Book.objects.get(pk=id)
  obj.delete()
  messages.success(request, 'データの削除に成功しました。')
  return redirect(reverse('list'))

main/templates/main/book_list.html
{% extends 'main/layout.html' %}

{% block main %}
<table class="table">
    <thead>
        <tr>
            <th>ISBNコード</th><th>書名</th><th>価格</th><th>出版社</th><th>刊行日</th>
        </tr>
    </thead>
    <tbody>
        {% for b in books %}
        <tr>
            <td>{{ b.isbn }}</td>
            <td>{{ b.title }}</td>
            <td>{{ b.price }}</td>
            <td>{{ b.publisher }}</td>
            <td>{{ b.published|date:'DATE_FORMAT' }}</td>
        {% endfor %}
        </tbody>
    </table>
    {{ data | unordered_list }}
    {% endblock %}

main/templates/main/escape.html
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
<title>速習 Django</title>
</head>
<body>
    {{ msg|safe }}
    {% autoescape off %}
    {{msg}}
    {% endautoescape %}
    {% autoescape off %}
    {{msg|escape}}
    {% endautoescape %}
    <br />
    {{ msg|striptags }}
</body>
</html>

main/templates/main/forempty.html
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
<title>速習 Django</title>
</head>
<body>
    {% for m in members %}
    <li>{{ m }}</li>
    {% empty %}
    <p>データは存在しません。</p>
    {% endfor %}
</body>
</html>

main/templates/main/forloop.html
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
<title>速習 Django</title>
</head>
<body>
    <table class="table">
        <thead>
            <tr>
                <th>値</th>
                <th>counter</th>
                <th>counter0</th>
                <th>rev</th>
                <th>rev0</th>
                <th>first</th>
                <th>last</th>
            </tr>
        </thead>
        <tbody>
            {% for week in weeks %}
            <tr>
                <td>{{ week}} </td>
                <td>{{ forloop.counter}} </td>
                <td>{{ forloop.counter0}} </td>
                <td>{{ forloop.revcounter}} </td>
                <td>{{ forloop.revcounter0}} </td>
                <td>{{ forloop.first}} </td>
                <td>{{ forloop.last}} </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

main/templates/main/form_process.html
{% extends 'main/layout.html' %}

{% block main %}
<table class="table">
  <tr>
    <th>{{ form.isbn.label }}</th>
    <td>{{ form.cleaned_data.isbn }}</td>
  </tr>
  <tr>
    <th>書名</th>
    <td>{{ form.cleaned_data.title }}</td>
  </tr>
  <tr>
    <th>価格</th>
    <td>{{ form.cleaned_data.price }}円</td>
  </tr>
  <tr>
    <th>出版社</th>
    <td>{{ form.cleaned_data.publisher }}</td>
    <!-- <td>{{ form.cleaned_data.publisher | join:',' }}</td> -->
  </tr>
  <tr>
    <th>刊行日</th>
    <td>{{ form.cleaned_data.published }}</td>
  </tr>
</table>
{% endblock %}

main/templates/main/fortag.html
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
<title>速習 Django</title>
</head>
<body>
    <!-- a.半角空白10個の文字列を生成 -->
     {% with ''|center:10 as range %}
    <!-- b.10桁の文字列を順に処理 -->
     {% for _ in range %}
     <p>こんにちは、赤ちゃん！</p>
     {% endfor %}
     {% endwith %}
</body>
</html>

main/templates/main/groupby.html
{% extends 'main/layout.html' %}

{% block main %}
<ul>
    <!-- b.グループ単位 -->
     {% for item in groups %}
     <li>{{ item.publisher }}: {{ item.pub_count }}冊</li>
     {% endfor %}
</ul>
{% endblock %}

main/templates/main/ifchanged.html
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
<title>速習 Django</title>
</head>
<body>
    <!-- a.取得した要素（タプル）からday/bodyをアンパック -->
     {% for day, body in schedule %}
    <!-- b.dayが変化した時にだけ出力 -->
     {% ifchanged day %}
     <h3>{{ day }}日</h3>
     {% endifchanged %}
     <p>{{ body }}</p>
     {% endfor %}
</body>
</html>

main/templates/main/rel.html
{% extends 'main/layout.html' %}

{% block main %}
<h3>「{{book.title}}」のレビュー</h3>
<hr />
<ul>
    {% for rev in book.review_set.all %}
    <li>{{rev.body}} ({{rev.name}})</li>
    {% endfor %}
</ul>
{% endblock %}

main/templates/main/rel2.html
<table class="table">
    <thead>
        <tr>
            <th>ISBNコード</th><th>書名</th><th>著者<th><th>価格</th>
        </tr>
    </thead>
    <tbody>
        {% for b in books %}
        <tr>
            <td>{{ b.isbn }}</td>
            <td>{{ b.title }}</td>
            <td>{% for a in b.author_set.all %}{{ a.name }} {% endfor %}</td>
            <td>{{ b.price}}円</td>
        </dr>
        {% endfor %}
    </tbody>
</table>

main/templates/main/slice.html
{% extends 'main/layout.html' %}


{% block main %}
<ul>
    <li>{{ data | slice:':2' }}</li>
    <li>{{ data | slice:'2' }}</li>
    <li>{{ data | slice:'2:' }}</li>
    <li>{{ data | slice:'1:4' }}</li>
</ul>
{% endblock %}

main/templates/main/static.html
{% extends 'main/layout.html' %}

{% block main %}
{% load static %}
<img src="{% static 'img/wings2.jpg' %}" />
{% endblock %}

main/templates/main/temp.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8" />
        <title>速習 Python</title>
    </head>
    <body>
        <p>{{ msg }}</p>
    </body>
</html>

main/templates/main/temptag.html
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
<title>速習 Django</title>
</head>
<body>
    {% templatetag openblock %}now 'DATETIME_FORMAT'{% templatetag closeblock %}
</body>
</html>